name: HTML Lint

on:
  pull_request:
    paths:
      - "index.html"
      - ".htmlhintrc"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/htmllint.yml"

jobs:
  htmlhint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run htmlhint
        run: npm run lint

